accounts/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import include, url
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)




app_name='accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name="signup"),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^logout/$',views.logout_view, name="logout"),
]

blog/urls.py
from django.conf.urls import include, url
from . import views
from django.urls import include, path
from .views import ListadoCompras,CrearCompra,ModificarCompra
from django.views.generic import TemplateView


app_name ='blog'

urlpatterns = [
    url(r'^$', views.main,name='home'),
    url(r'^registro$', views.registro,name='registro'),
    path('ajax/load-cities/', views.load_ciudades, name='load_ciudades'),
    url(r'^producto$', views.producto,name='producto'),
    url(r'^producto/(?P<pk>[0-9]+)/$', views.producto_detail, name='producto_detail'),
    url(r'^modificar_compra/(?P<pk>.+)/$',ModificarCompra.as_view(), name="modificar_compra"),
    url(r'^base', views.base_layout, name='base'),
    url(r'^compras_list', ListadoCompras.as_view(), name="compras_list"),
    url(r'^crear_compra/$', CrearCompra.as_view(), name="crear_compra"),
    path('manifest.json', TemplateView.as_view(template_name='manifest.json', content_type='application/json')),
    path('OneSignalSDKWorker.js', TemplateView.as_view(template_name='OneSignalSDKWorker.js', content_type='application/x-javascript')),
    path('OneSignalSDKWorker.js', TemplateView.as_view(template_name='OneSignalSDKWorker.js', content_type='application/x-javascript')),
    path('onesignal_register/', views.onesignal_register, name='onesignal_register'),
    
]

listocompra/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from blog.quickstart import views
from django.contrib.auth import views as auth_views
from rest_framework import routers
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.urls import path

router = routers.DefaultRouter()

router.register(r'Tiendas', views.TiendaViewSet)
router.register(r'Ciudad', views.CiudadViewSet)
router.register(r'Region', views.RegionViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^password/', include('password_reset.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),   
    url(r'^', include(router.urls)),
    path('', include('pwa.urls')),
]

blog/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.db.models import Sum,Count
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.contrib.auth.models import User
import django
from django.conf import settings

# Create your models here.

class Region(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Ciudad(models.Model):
    region = models.ForeignKey(Region,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Tienda(models.Model):
    nombre = models.CharField(max_length=30, blank=False,unique=True)
    sucursal = models.CharField(max_length=30)
    direccion = models.CharField(max_length=30, blank=False)
    region = models.ForeignKey(Region,related_name='regi', on_delete=models.SET_NULL, null=True)
    ciudad = models.ForeignKey(Ciudad,related_name='city', on_delete=models.SET_NULL, null=True)
    estado_choices = (
        ('PENDIENTE', 'Pendiente'),
        ('APROBADO', 'Aprobado'),
    )
    estado = models.CharField(max_length=30, choices=estado_choices, default='PENDIENTE')

    def publish(self):
        self.save()

    def __str__(self):
        return self.nombre
    

class Lista(models.Model):
    nombre = models.CharField(max_length=30, blank=False,default='')
    totalAgregados = models.IntegerField(validators=[MinValueValidator(1)],default=0)
    totalComprados = models.IntegerField(validators=[MinValueValidator(1)],default=0)
    costoReal =  models.IntegerField(validators=[MinValueValidator(1)],default=0)
    costoPresupuestado = models.IntegerField(validators=[MinValueValidator(1)],default=0)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.nombre

    def publish(self):
        
        self.save()


class Producto(models.Model):
    
    nombre = models.CharField(max_length=30, blank=False)
    costoPresupuestado = models.IntegerField(validators=[MinValueValidator(1)],default=0)
    costoReal = models.IntegerField(validators=[MinValueValidator(1)],default=0)
    notasAdicionales = models.CharField(max_length=50)
    estado_choices = (
        ('COMPRADO', 'Comprado'),
        ('PENDIENTE', 'Pendiente'),
    )
    estado = models.CharField(max_length=30, choices=estado_choices, default='PENDIENTE')
    tienda = models.ForeignKey(Tienda, on_delete=models.SET_NULL, null=True ,related_name='est',limit_choices_to={'estado': 'APROBADO'})
    lista = models.ForeignKey(Lista, on_delete=models.SET_NULL, null=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.nombre

    def getestado(self):
        return self.tienda.estado




   

   


    

blog/quickstart/views.py
from rest_framework import viewsets
from blog.quickstart.serializers import  TiendaSerializer, CiudadSerializer,RegionSerializer
from blog.models import Tienda,Ciudad,Region


class TiendaViewSet(viewsets.ModelViewSet):
 
    queryset = Tienda.objects.all()
    serializer_class = TiendaSerializer

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ciudad'].queryset = Ciudad.objects.none()

        if 'region' in self.data:
                try:
                    region_id = int(self.data.get('region'))
                    self.fields['ciudad'].queryset = Ciudad.objects.filter(region_id=region_id).order_by('nombre')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty Ciudad queryset
        elif self.instance.pk:
            self.fields['ciudad'].queryset = self.instance.region.ciudad_set.order_by('nombre')


class RegionViewSet(viewsets.ModelViewSet):
 
    queryset = Region.objects.all()
    serializer_class = RegionSerializer

class CiudadViewSet(viewsets.ModelViewSet):
 
    queryset = Ciudad.objects.all()
    serializer_class = CiudadSerializer

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Ciudad,Region,Producto,Tienda,Lista
from .forms import TiendaForm,ProductoForm,ListaForm, DetalleCompraFormSet,DetalleCompraFormSetV2
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,UpdateView
from django.urls import reverse_lazy
from django.http import HttpResponse,HttpResponseRedirect
from django.db.models import Sum,Count
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
User = get_user_model()


# Create your views here.

def main(request):
    return render(request, 'blog/index.html')
    

def registro(request):
    tienda = TiendaForm()
    return render(request, 'blog/registro.html',{'tienda':tienda})

def registro(request):
    if request.method == "POST":
        tienda = TiendaForm(request.POST)
        if tienda.is_valid():
            tienda = tienda.save(commit=False)
            tienda.save()
            return redirect('blog:home')
    else:
        tienda = TiendaForm()
    return render(request, 'blog/Registro.html', {'tienda': tienda})


def load_ciudades(request):
    region_id = request.GET.get('region')
    ciudades = Ciudad.objects.filter(region_id=region_id).order_by('nombre')
    return render(request, 'blog/ciudad_dropdown_list_options.html', {'ciudades': ciudades})

def producto(request):
    producto = ProductoForm()
    return render(request,'blog/producto.html',{'producto':producto})


def producto(request):
    if request.method == "POST":
        producto = ProductoForm(request.POST)
        if producto.is_valid():
            producto = producto.save(commit=False)
            producto.save()
            return redirect('blog:home')
    else:
        producto = ProductoForm()
    return render(request, 'blog/producto.html', {'producto':producto})

def producto_detail(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    return render(request, 'blog/compras_detail.html', {'productos': producto})



class ListadoCompras(ListView):
    model = Lista
    template_name = 'blog/compras_list.html'
    context_object_name = 'compras'

class CrearCompra(CreateView):
    model = Lista
    
    template_name = 'blog/lista_add.html'
    form_class = ListaForm
  
    success_url = reverse_lazy('blog:compras_list')
    
    def get(self, request, *args, **kwargs):
        """Primero ponemos nuestro object como nulo, se debe tener en
        cuenta que object se usa en la clase CreateView para crear el objeto"""
        self.object = None
        #Instanciamos el formulario de la Compra que declaramos en la variable form_class
        form_class = self.get_form_class()
        form = self.get_form(form_class)
     
        
        #Instanciamos el formset
        detalle_orden_compra_formset=DetalleCompraFormSet()
        #Renderizamos el formulario de la compra y el formset
        return self.render_to_response(self.get_context_data(form=form ,detalle_compra_form_set=detalle_orden_compra_formset))

    def post(self, request, *args, **kwargs):
        #Obtenemos nuevamente la instancia del formulario de Compras
        form_class = self.get_form_class()
        form = self.get_form(form_class)
      
        
        #Obtenemos el formset pero ya con lo que se le pasa en el POST
        detalle_compra_form_set = DetalleCompraFormSet(request.POST)
        """Llamamos a los métodos para validar el formulario de Compra y el formset, si son válidos ambos se llama al método
        form_valid o en caso contrario se llama al método form_invalid"""
        if form.is_valid() and detalle_compra_form_set.is_valid():
            user= form.save(commit=False)
            value = User.objects.get(username=request.user)
            user.author = value
            user.save()
            return self.form_valid(form, detalle_compra_form_set)
        else:
            return self.form_invalid(form, detalle_compra_form_set)

        
    def form_valid(self, form, detalle_compra_form_set):
        #Aquí ya guardamos el object de acuerdo a los valores del formulario de Compra
        
        
        self.object = form.save()   
        
        #Utilizamos el atributo instance del formset para asignarle el valor del objeto Compra creado y que nos indica el modelo Foráneo
        detalle_compra_form_set.instance = self.object
        
        #Finalmente guardamos el formset para que tome los valores que tiene
        detalle_compra_form_set.save()
        #Redireccionamos a la ventana del listado de compras
        return HttpResponseRedirect(self.success_url)


    def form_invalid(self, form, detalle_compra_form_set):
        #Si es inválido el form de Compra o el formset renderizamos los errores
        return self.render_to_response(self.get_context_data(form=form,detalle_compra_form_set = detalle_compra_form_set))


class ModificarCompra(UpdateView):
    model = Lista
    template_name = 'blog/lista_add.html'
    form_class = ListaForm
    success_url = reverse_lazy('blog:compras_list')

    def get(self, request, *args, **kwargs):
        #Obtenemos el objeto Compra
        self.object = self.get_object()
        #Obtenemos el formulario
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        #Obtenemos los detalles de la compra
        detalles = Producto.objects.filter(lista=self.object).order_by('pk')
        detalles_data = []
        #Guardamos los detalles en un diccionario
        for detalle in detalles:
            d = {'nombre': detalle.nombre,
                'costoPresupuestado': detalle.costoPresupuestado,
                'costoReal': detalle.costoReal,
                'notasAdicionales': detalle.notasAdicionales,
                'estado': detalle.estado,
                'tienda': detalle.tienda,
                }
            detalles_data.append(d)
          
        #Ponemos como datos iniciales del formset el diccionario que hemos obtenido
        
        detalle_compra_form_set = DetalleCompraFormSetV2(initial=detalles_data)
        
         #Renderizamos el formulario y el formset
        return self.render_to_response(self.get_context_data(form=form,
                                                         detalle_compra_form_set=detalle_compra_form_set))


    def post(self, request, *args, **kwargs):
    #Obtenemos el objeto compra
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_compra_form_set = DetalleCompraFormSetV2(request.POST)
        #Verificamos que los formularios sean validos
        if form.is_valid() and detalle_compra_form_set.is_valid():
            return self.form_valid(form, detalle_compra_form_set)
        else:
            return self.form_invalid(form, detalle_compra_form_set)


    def form_valid(self, form, detalle_compra_form_set):
        #Guardamos el objeto compra
        self.object = form.save()
  
        detalle_compra_form_set.instance = self.object
        #Eliminamos todas los detalles de la compra
        Producto.objects.filter(lista = self.object).delete()
        #Guardamos los nuevos detalles de la compra
        detalle_compra_form_set.save()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form, detalle_compra_form_set):
        #Renderizamos los errores
        return self.render_to_response(self.get_context_data(form=form,
                                                         detalle_compra_form_set = detalle_compra_form_set))


def base_layout(request):
	template='blog/base.html'
	return render(request,template)

# OneSignal Register

@login_required
def onesignal_register(request):
  '''Receives the onesignal playerid of this user'''
  profile = Profile.objects.get(user=request.user) # The model where you will to save the profile.
  if request.POST.get('playerId'):
      profile.onesignal_playerId = request.POST.get('playerId')
      profile.save()
      return HttpResponse('Done')
  return HttpResponse('Something went wrong')



 


    







    








                                                       


  

    

blog/templates/blog/base.html
{% load static %}
<html>
{% load pwa %}

<head>
    {% progressive_web_app_meta %}
    <title>Neo Compra</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="msapplication-TileImage" content="static/icons/i1.png">
    <meta name="msapplication-TileColor" content="#2F3BA2">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'js/skel.min.js' %}"></script>
    <script src="{% static 'js/util.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <link rel="manifest" href="/manifest.json" />
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    <script>
        var OneSignal = window.OneSignal || [];
        OneSignal.push(function () {
            OneSignal.init({
                appId: "877d417d-3142-49d6-9823-87ac29a97486",
                autoRegister: false,
                notifyButton: {
                    enable: true,
                },
                allowLocalhostAsSecureOrigin: true,
            });
        });

        OneSignal.getUserId(function (userId) {
            console.log('player_id of the subscribed user is : ' + userId);
            // Make sure to change the URL for the correct path
            $.post("/onesignal-register/",
                {
                    playerId: userId,
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                },
                function (data, status) {
                    console.log("Data: " + data + "\nStatus: " + status);
                });
        });
    </script>
</head>

<body>
    <!-- Header -->
    <header id="header">
        <nav class="left">
            <a href="#menu"><span>Menu</span></a>
        </nav>
        <a href="{% url 'blog:home' %}" class="logo">Neo Compra</a>
        {% if user.is_authenticated %}
        <nav class="right">

            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                Hola: {{ request.user }} {% csrf_token %}
                <button class="salir" type="submit">LogOut</button>
            </form>
        </nav>

        {% else %}

        <nav class="right sesion">

            <a href="{% url 'accounts:login' %}" class="button alt">LogIn</a>
        </nav>

        {% endif %}

        <!--<nav class="right2">
					<a href="login.html" class="button session">Cerrar Sesión</a>
				</nav>-->
    </header>

    <!-- Menu -->
    <nav id="menu">
        <ul class="links">
            <li><a href="{% url 'blog:home' %}">Inicio</a></li>
            <li><a href="generic.html">Quiénes Somos</a></li>
            <li><a href="#footer">Contacto</a></li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="actions vertical">
            <li>
                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    Hola : {{ request.user }} {% csrf_token %}
                    <br>
                    <br>
                    <button class="salir" type="submit">LogOut</button>
                </form>

            </li>
        </ul>
        {% else %}
        <ul class="actions vertical">

            <li><a href="{% url 'accounts:login' %}" class="button fit">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    {% block content %} {% endblock %}



    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <h2>Contacto</h2>
            <ul class="actions">
                <li><span class="icon fa-phone"></span> <a href="#">(+56) 959078635</a></li>
                <li><span class="icon fa-envelope"></span> <a href="#">info@neocompra.cl</a></li>
                <li><span class="icon fa-map-marker"></span> Camino uno 98, Valparaíso, Región Valparaíso</li>
            </ul>
        </div>
        <div class="copyright">
            &copy; Untitled. Design <a href="https://templated.co">TEMPLATED</a>. Images <a href="https://unsplash.com">Unsplash</a>.
        </div>
    </footer>

</body>


</html>

blog/templates/blog/ciudad_dropdown_list_options.html
<option value="">---------</option>
{% for ciudad in ciudades %}
<option value="{{ ciudad.pk }}">{{ ciudad.nombre }}</option>
{% endfor %}

blog/templates/blog/compras_list.html
{% extends 'blog/base.html' %} 
{% load static %} 
{% block content %}

<section id="one" class="wrapper">
        <div class="text-center 12u">
                <h3 class="">Lista de compras</h3>      
        </div>
        <div class="text-right">
                <a href="{% url 'blog:crear_compra' %}" class="btn btn-primary">
                        Crear
                </a> 
                <br>
        </div> 
        <br>   
    <table class="12u">
            <thead>
                <tr>
                    <th class="text-center">Nombre Lista</th>
                    <th class="text-center">total Agregados</th>
                    <th class="text-center">total Comprados</th>
                    <th class="text-center">Precio Presupuestado</th>
                    <th class="text-center">Precio Real</th>
                    <th class="text-center">Author</th>
                    <th class="text-center">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for lista in compras %}
                {% if lista.author == request.user %}
                <tr class="text-center">
                    <td>{{ lista.nombre }}</td>
                    <td>{{ lista.totalAgregados}}</td>
                    <td>{{ lista.totalComprados}}</td>
                    <td>{{ lista.costoPresupuestado}}</td>
                    <td>{{ lista.costoReal}}</td>
                    <td>{{ lista.author }}</td>
                    <td class="text-center">
                        <a href="#" class="btn">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        <a href="{% url 'blog:modificar_compra' pk=lista.pk %}" class="btn">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    </td>
                </tr>
            {% endif %}
              {% endfor %}
            </tbody>
        </table>
</section>

<script>

    $(document).ready(function () {
        var table = $('#tabla').dataTable({
            "language": {
                url: "/static/localizacion/es_ES.json"
            }
        });
    });
</script>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<!-- Banner -->
<section id="banner">
	<div class="content">
		{% if user.is_authenticated %}
		<h1>¡Organiza Tus Compras!</h1>
		<p>¡Con Neo Compra organiza todas tus compras en un solo lugar!</p>

		{% else %}
		
		<h1>Facilita las compras</h1>
		<p>¡Con Neo Compra organiza todas tus compras en un solo lugar!</p>
		<ul class="actions">
			<li><a href="{% url 'accounts:signup' %}" class="button scrolly">REGÍSTRATE GRATIS</a></li>
		</ul>
		{% endif %}
	</div>
</section>

<!-- One -->
<section id="one" class="wrapper">
	<div class="inner flex flex-3">
		<div class="flex-item left">
			<div>
				<h3>Ahorra tiempo</h3>
				<p>Morbi in sem quis dui plalorem ipsum<br /> euismod in, pharetra sed ultricies.</p>
			</div>
			<div>
				<h3>Ahorra dinero</h3>
				<p>Tristique yonve cursus jam nulla quam<br /> loreipsu gravida adipiscing lorem</p>
			</div>
		</div>
		<div class="flex-item image fit round">
			<img src="{% static 'img/pic01.jpg' %}" alt="" />
		</div>
		<div class="flex-item right">
			<div>
				<h3>Organiza tus compras</h3>
				<p>Sed adipiscing ornare risus. Morbi estes<br /> blandit sit et amet, sagittis magna.</p>
			</div>
			<div>
				<h3>Rápido y sencillo</h3>
				<p>Pellentesque egestas sem. Suspendisse<br /> modo ullamcorper feugiat lorem.</p>
			</div>
		</div>
	</div>
</section>

<!-- Three -->
{% if user.is_authenticated %}
<section id="three" class="wrapper">
	<div class="inner flex flex-3">
		<div class="flex-item box">
			<div class="image fit">
				<a href="{% url 'blog:producto' %}"><img src="{% static 'img/pic02.jpg' %}" alt="" /></a>
				
			</div>
			<div class="content">
				<h3>Productos</h3>
				<p>Placerat ornare. Pellentesque od sed euismod in, pharetra ltricies edarcu cas consequat.</p>
			</div>
		</div>
		<div class="flex-item box">
			<div class="image fit">
				<a href="{% url 'blog:compras_list' %}"><img src="{% static 'img/pic03.jpg' %}" alt="" /></a>
			</div>
			<div class="content">
				<h3>Listas de Compras</h3>
				<p>Morbi in sem quis dui placerat Pellentesque odio nisi, euismod pharetra lorem ipsum.</p>
			</div>
		</div>
		<div class="flex-item box">
			<div class="image fit">
				<a href="{% url 'blog:registro' %}"><img src="{% static 'img/pic04.jpg' %}" alt="" /></a>
				
			</div>
			<div class="content">
				<h3>Tiendas</h3>
				<p>Nam dui mi, tincidunt quis, accu an porttitor, facilisis luctus que metus vulputate sem magna.</p>
			</div>
		</div>
	</div>
</section>
{% endif %} {% endblock %}

blog/templates/blog/lista_add.html
{% extends 'blog/base.html' %} {%load static%} {% block content %}


<section id="main" class="wrapper">
        <div class="inner">
                {% if object %}
                <form role="form" action="{% url 'blog:modificar_compra' object.pk %}" method="post">
                        <h3>Modificar Compra</h3>
                {% else %}
                <form role="form" action="{% url 'blog:crear_compra' %}" method="post">
                        <h3>Crear Compra</h3>
                {% endif %}
                        {% csrf_token %}
                        <div class="panel panel-default">
                                <div class="panel-body">
                                        {{ form.as_p }} 
                                       
                                        {{ detalle_compra_form_set.management_form }}
                                        <hr> {% for detalle_compra_form in detalle_compra_form_set %}
                                        <div class="row">
                                                <div class="col-lg-8"> 
                                                        <label>Producto</label>
                                                        {{ detalle_compra_form.nombre }}
                                                </div>
                                                <div class="col-lg-4">

                                                        <label>costo Presupuestado</label>

                                                        {{ detalle_compra_form.costoPresupuestado }}
                                                </div>
                                                <div class="col-lg-4">
                                                                <br>
                                                                
                                                        <label>Costo Real</label>

                                                        {{ detalle_compra_form.costoReal }}
                                                </div>
                                               
                                                <div class="col-lg-4">
                                                                <br>
                                                        <label>Notas Adicionales</label>

                                                        {{ detalle_compra_form.notasAdicionales }}
                                                </div>
                                                <div class="col-lg-4">
                                                                <br>
                                                                <label>Tienda</label>
                                                                {{ detalle_compra_form.tienda }}

                                                                
                                                </div>
                                    
                                                <div class="col-lg-4">
                                                                <br>
                                                        
                                                        <label>Estado</label>
                                                        {{ detalle_compra_form.estado }}
                                                        
                                                </div>

                                        </div>
                                        <hr> {% endfor %}

                                </div>
                        </div>

                        <div class="col-lg-12 text-right">
                                
                                
                                <input type="submit" class="button scrolly" name="submit" value="Guardar">
                                <a type="button" class="button special" href="{% url 'blog:compras_list' %}">
                                        Cancelar
                                </a>
                                <br>
                               
                        </div>
                        <br>
                </form>


        </div>
</section>





{% endblock %}

blog/templates/blog/producto.html
{% extends 'blog/base.html' %} {% block content %} {% csrf_token %}

<section id="main" class="wrapper">
    <div class="inner">
        <!-- Elements -->
        <h2 id="elements">Ingresa un Producto</h2>
        <div class="row 200% form-login">
            <div class="12u">

                <form method="POST" class="post-form">
                    {% csrf_token %} {{ producto.as_p }}
                    
                    <br>
                    <input type="submit" name="submit" value="Registrar">
                    <input type="button" name="back" value="Volver" onclick="location.href='/'">
                </form>
            </div>
        </div>

    </div>
</section>

{% endblock %}

blog/templates/blog/registro.html
{% extends 'blog/base.html' %} {% block content %}

<section id="main" class="wrapper">
    <div class="inner">
        <!-- Elements -->
        
        <div class="row 200% form-login">
            <div class="12u">

                <br>
                <form id="formulario-perris" method="POST" data-cities-url="{% url 'blog:load_ciudades' %}" class="post-form">
                        <br>
                        <h1>¡Inscribe una tienda!</h1>
                        <br> {% csrf_token %} {{ tienda.as_p }}
                        <br>
                        <input type="submit" name="submit" value="Enviar">
                        <a href="{% url 'blog:home' %}"><input type="button" name="back" value="Volver"></a>
                
                    </form>
                
                    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                    <script>
                        $("#id_region").change(function () {
                            var url = $("#formulario-perris").attr("data-cities-url");  // get the url of the `load_cities` view
                            var regionId = $(this).val();  // get the selected country ID from the HTML input
                
                            $.ajax({                       // initialize an AJAX request
                                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                                data: {
                                    'region': regionId       // add the country id to the GET parameters
                                },
                                success: function (data) {   // `data` is the return of the `load_cities` view function
                                    $("#id_ciudad").html(data);  // replace the contents of the city input with the data that came from the server
                                }
                            });
                
                        });
                    </script>
            </div>
        </div>

    </div>
</section>

{% endblock %}